language: java
sudo: false
before_install:
  - chmod +x mvnw
script: mvn clean install
notifications:
  slack:
    on_success: always
  email:
    - akalanka345@gmail.com
    - pasan.peiris01@gmail.com
    - benuka02@gmail.com 
